name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout someengineering/resoto
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')
        uses: actions/checkout@v2
        with:
          repository: someengineering/resoto
          path: resoto
      - name: Generate resotocore API Swagger UI
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')
        uses: Legion2/swagger-ui-action@v1
        with:
          output: static/api
          spec-file: resoto/resotocore/core/static/api-doc.yaml
      - name: Install dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: yarn install --frozen-lockfile
      - name: Lint
        if: github.event_name == 'pull_request'
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Deploy
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
